import type { Config } from 'tailwindcss'
import tailwindcssAnimate from 'tailwindcss-animate'

const config: Config = {
  darkMode: ['class'],
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: { DEFAULT: '#3B5A80', dark: '#2D4766', light: '#EEF3F9' },
        dark: { DEFAULT: '#0F172A', deeper: '#0A1019' },
        accent: { DEFAULT: '#14B8A6', dark: '#0F766E', light: '#CCFBF1' },
        discount: { DEFAULT: '#D9457A', light: '#FDE8EF' },
        navy: { DEFAULT: '#3B5A80', dark: '#2D4766', deep: '#0F172A', deeper: '#0A1019' },
        teal: { DEFAULT: '#14B8A6', dark: '#0F766E', light: '#CCFBF1' },
        'bg-primary': '#FFFFFF',
        'bg-secondary': '#E8EEF5',
        'bg-tertiary': '#E2E8F0',
        'bg-soft': '#F8FAFC',
        'bg-muted': '#E8EEF5',
        'text-primary': '#0F172A',
        'text-secondary': '#374151',
        'text-tertiary': '#6B7280',
        'text-muted': '#6B7280',
        'border-default': 'rgba(59,90,128,.12)',
        'border-soft': 'rgba(59,90,128,.12)',
        'border-base': 'rgba(59,90,128,.2)',
        success: '#14B8A6',
        'success-light': '#CCFBF1',
        warning: '#B45309',
        'warning-light': '#FEF3C7',
        error: '#E0455A',
        'error-text': '#DC2626',
        'error-light': '#FEE2E2',
        info: '#3B5A80',
        'info-light': '#EEF3F9',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        'hsl-primary': { DEFAULT: 'hsl(var(--primary-hsl))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        'hsl-accent': { DEFAULT: 'hsl(var(--accent-hsl))', foreground: 'hsl(var(--accent-foreground))' },
      },
      fontFamily: { sans: ['IRANSansX', 'Vazirmatn', 'system-ui', 'sans-serif'] },
      boxShadow: {
        soft: '0 1px 3px rgba(15,23,42,.06)',
        card: '0 1px 2px rgba(15,23,42,.04), 0 4px 12px rgba(15,23,42,.04)',
        'card-hover': '0 8px 24px rgba(15,23,42,.08)',
        elevated: '0 16px 40px rgba(15,23,42,.13)',
      },
      borderRadius: {
        xs: '6px', sm: '8px', md: '12px', lg: '16px', xl: '20px', '2xl': '24px', '3xl': '28px', full: '9999px',
      },
      height: { navbar: '72px' },
      spacing: {
        section: '4rem', 'section-lg': '5rem', 'section-mobile': '3.5rem', 'section-desktop': '5rem',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'fade-in': { from: { opacity: '0', transform: 'translateY(12px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'scale-in': { from: { opacity: '0', transform: 'scale(.97)' }, to: { opacity: '1', transform: 'scale(1)' } },
        'slide-in-right': { from: { transform: 'translateX(100%)' }, to: { transform: 'translateX(0)' } },
        'slide-in-left': { from: { transform: 'translateX(-100%)' }, to: { transform: 'translateX(0)' } },
        shimmer: { from: { backgroundPosition: '-200% 0' }, to: { backgroundPosition: '200% 0' } },
        marquee: { from: { transform: 'translateX(0)' }, to: { transform: 'translateX(-50%)' } },
      },
      animation: {
        'accordion-down': 'accordion-down 200ms ease-out',
        'accordion-up': 'accordion-up 200ms ease-out',
        'fade-in': 'fade-in 360ms cubic-bezier(.16,1,.3,1)',
        'scale-in': 'scale-in 200ms cubic-bezier(.16,1,.3,1)',
        'slide-in-right': 'slide-in-right 200ms ease-out',
        'slide-in-left': 'slide-in-left 200ms ease-out',
        shimmer: 'shimmer 1.2s ease-in-out infinite',
        marquee: 'marquee 32s linear infinite',
      },
    },
  },
  plugins: [tailwindcssAnimate],
}

export default config
